name: Build APK

on:
  push:
    branches: [ "*" ]  # Tüm branch'lerde çalışsın
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: OxClient-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

